/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemaEmprestimoGUI;

import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maria
 */
public class relatorioCusto extends javax.swing.JFrame {

    /**
     * Creates new form relatorioCusto
     */
    public relatorioCusto() {
        initComponents();
        loadMockData();
    }
    
    private void loadMockData() {
        DefaultTableModel model = (DefaultTableModel) toolsTable.getModel();
        
        //Dados mockados
        Object[][] mockData = {
            {1, "Martelo", "Tramontina", 25.00},
            {2, "Chave de Fenda", "Bosch", 15.00},
            {3, "Serrote", "Stanley", 45.00},
            {4, "Alicate", "Vonder", 30.00}
        };
        
        double totalCost = 0;
        
        //Adicionar dados mockados ao modelo da tabela e calcular o total de custo
        for (Object[] row : mockData) {
            model.addRow(row);
            totalCost += (double) row[3]; //Assumindo que o custo de aquisição é do tipo double
            
        }
        
        totalCostLabel.setText("Total de Custo: R$" + String.format("%.2f", totalCost));
        
    }
    
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new relatorioCusto().setVisible(true));
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        toolsTable = new javax.swing.JTable();
        totalCostLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Ferramentas e Total de Custo");

        toolsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Marca", "Custo de Aquisição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        toolsTable.setShowGrid(true);
        jScrollPane1.setViewportView(toolsTable);

        totalCostLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        totalCostLabel.setText("Total de Custo: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totalCostLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalCostLabel)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable toolsTable;
    private javax.swing.JLabel totalCostLabel;
    // End of variables declaration//GEN-END:variables
}
